### ISSUE TITLE
Blur Everything Beneath BlurringView

### ISSUE THREAD

**Issue by redstonedev** [500px/500px-android-blur#4]
Is it possible to make the BlurringView blur everything that's beneath it? (Not only its sibling views.)

-R

**Comment by luojun** [comment]
It's possible, so long as you organize the view hierarchy in a way such that "everything beneath the BlurringView" is contained in a single view (the blurred view).

**Comment by luojun** [comment]
Replied to your comment on GitHub.

If I understand it correctly, what you want is this: (1) the Sliding Up
Panel will not hide the Main Content underneath it but will instead blur
it; (2) you are also adding more content into the Sliding Up Panel.

Here's what you could try: put the BlurringView as the lowest subview (in
z-order) among Sliding Up Panel's subviews and make it match parent so that
it's always as big as the Sliding Up Panel. That way, you can still get the
appropriate transformations. There may be more things to tweak here. You'll
have to find out and figure it out.

In general, I don't think the solution should be making the BlurringView a
ViewGroup. If you really want to do that, that's possible too. But you'll
need to tweak the BlurringView's onDraw method so that it can appropriately
combine blurring with drawing of other subviews of the ViewGroup. Note also
that Android by default does not call the onDraw method of ViewGroup.

Best,
Jun
